image: node:11.1.0-alpine

stages:
  - init
  - test

init:
  stage: init
  script:
    - apk add --update --no-cache python g++ make
    - apk add fftw-dev --update --no-cache --repository https://dl-3.alpinelinux.org/alpine/edge/main/
    - apk add vips-dev --update --no-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/
    - yarn global add node-gyp
    - yarn install --silent
  artifacts:
    paths:
      - node_modules/

lint:
  stage: test
  script:
    - yarn lint
  dependencies:
    - init

unit-test:
  stage: test
  script:
    - yarn test:unit
  dependencies:
    - init

visual-regression-test:
  stage: test
  before_script:
    - apk add --update --no-cache git chromium nss
    - apk add fftw-dev --update --no-cache --repository https://dl-3.alpinelinux.org/alpine/edge/main/
    - apk add vips-dev --update --no-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/
    - yarn install --silent
    - yarn build
    - yarn storybook:build
  script:
    - yarn test:visual:ci
  dependencies:
    - init
  artifacts:
    when: on_failure
    paths:
      - src/__tests__/__image_snapshots__/__diff_output__/

security:
  stage: test
  script:
    - yarn security
  dependencies:
    - init
  allow_failure: true

outdated:
  stage: test
  script:
    - yarn outdated
  only:
    - master
  allow_failure: true
